### ISSUE TITLE
What speed is really needed?

### ISSUE THREAD

**Issue by vitaly-t** [Pranay92/Competitve-JavaScript#1]
> This includes programs like calculating 25000th prime number, which in JavaScript is around 10x slower than languages like c,c++ using the same algorithm

It takes about 1/30 of a second to calculate 25,000th prime number in JavaScript. How fast do you want it? :) :) :)

**Comment by Pranay92** [comment]
Its when using a brute force approach, not using mathematical formulae. (which most people will not know)

Have a look at this:
https://www.youtube.com/watch?v=UJPdhx5zTaw

**Comment by vitaly-t** [comment]
Thank you for the video. I have watched it and posted my comment there, which I'm re-posting here:

This is kind of funny, that after so much talking about that primes calculation algorithm and optimizing the heck out of it you arrived with 0.044s to calculate the 25,000th prime. Also your calculation is wrong, you calculated the 24,999th prime, by the way (the first prime is 2), and the 25,000th prime is 287117.

I didn't know most of what was explained in the video, but in my first take at the primes calculation it took only 0.025s to calculate the 25,000th prime :)

Here's the entire test:

``` javascript
function nextPrime(value) {
    if (value > 2) {
        var i, q;
        do {
            i = 3;
            value += 2;
            q = Math.floor(Math.sqrt(value));
            while (i <= q && value % i) {
                i += 2;
            }
        } while (i <= q);
        return value;
    }
    return value === 2 ? 3 : 2;
}

var value, start = Date.now();
for (var i = 0; i < 25000; i++) {
    value = nextPrime(value);
}
console.log('Value:', value);
console.log('Time:', Date.now() - start);
```

**Comment by Pranay92** [comment]
The video is from 2012 and the v8 and the other runtime as changed drastically over these years and thus you're getting faster execution.

Also, the approach was to first start writing code as similar to c++ as possible and then just optimizing the parts that are needed to make it faster. With bare minimum c++(brute force) you can write the same example that can execute in around 1-2 secs, while JS with same algorithm will take ~15 seconds! 

We need to find ways that make JS as efficient and thats exactly the point of creating this repo and adding sources which helps us to wirte code that runs faster, is memory efficient and also overcomes some of the other limitations. 

Thanks for the above code.

**Comment by vitaly-t** [comment]
You are welcome.

Oh, and the point of what I wrote.... when talking about optimization, It is not good to neglect to mention that optimizing the algorithm would always yield better improvements than any other types of optimization described in the video. But the author said nothing about it. That's why I produced my example and said it was funny, after so much optimization the final result still sucked against a simple algorithm optimization.

**Comment by Pranay92** [comment]
I'm closing this since I think we had sufficient discussion over this topic. Will try to include your code example when I have time.

**Comment by vitaly-t** [comment]
Just so, something strange about that algorithm, when I converted it into C++, not only I couldn't get it to work any faster, but for large tests, like the first 1,000,000 primes I'm getting speeds that are 2 times slower than in JavaScript. I don't know how this is even possible.

The test below runs for about 12 seconds, even though in JavaScript it does in 5 seconds. And that's running in Release 64-bit mode, with all speed optimizations turned on.

Any idea how this is even possible?

``` c++
#include "stdafx.h"
#include <windows.h>
#include "math.h"

ULONG64 nextPrime(ULONG64 value) {
    if (value > 2) {
        __int64 i, q;
        do {
            i = 3;
            value += 2;
            q = floor(sqrt((long double)value));
            while (i <= q && value % i) {
                i += 2;
            }
        } while (i <= q);
        return value;
    }
    return value == 2 ? 3 : 2;
}

void _tmain(int argc, _TCHAR* argv[])
{
    ULONG64 value = 0;
    DWORD start = GetTickCount();
    for (int i = 0; i < 1000000; i++)
    {
        value = nextPrime(value);
    }
    printf("\nTime: %d", GetTickCount() - start);
    printf("\nValue: %d", value);
    getchar();
}
```
